run: css/skeleton.css
	python3 -m http.server

css/skeleton.css:
	mkdir -p css
	curl https://raw.githubusercontent.com/dhg/Skeleton/master/css/normalize.css -o css/normalize.css
	curl https://raw.githubusercontent.com/dhg/Skeleton/gh-pages/dist/css/skeleton.css -o css/skeleton.css
